name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - id: real_sha
        run: echo "result=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)" >> "$GITHUB_OUTPUT"
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: tfsort --version
          gitref: ${{ steps.real_sha.outputs.result }}
